hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper & waybar & hyprsunset & hypridle & dunst")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)
